# Generated by Django 3.2.24 on 2024-12-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=20)),
                ('slider_description', models.CharField(max_length=50)),
                ('slider_photo', models.ImageField(default='uploads/sliders/sliders.jpg', upload_to='uploads/sliders')),
            ],
        ),
    ]
