# Generated by Django 3.2.24 on 2024-12-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliders',
            name='slider_description',
            field=models.CharField(max_length=1000),
        ),
    ]
