# Generated by Django 3.2.24 on 2024-12-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0003_alter_sliders_slider_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_trending_headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trending_photo', models.ImageField(default='uploads/main_trending/main.jpg', upload_to='uploads/main_trending')),
                ('type_of_headline', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('brief_description', models.TextField()),
                ('writter_photo', models.ImageField(default='uploads/writter/writter.jpg', upload_to='uploads/writters')),
                ('writter_name', models.CharField(max_length=30)),
            ],
        ),
    ]
