# Generated by Django 3.2.24 on 2024-12-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0004_main_trending_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_trending_headline',
            name='trending_title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
