# Generated by Django 3.2.24 on 2024-12-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0005_main_trending_headline_trending_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_trending_headline',
            name='type_of_headline',
            field=models.CharField(max_length=200),
        ),
    ]
