# Generated by Django 3.2.24 on 2024-12-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0006_alter_main_trending_headline_type_of_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_trending_headline',
            name='trending_description',
            field=models.TextField(default=''),
        ),
    ]
