# Generated by Django 3.2.24 on 2024-12-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0007_main_trending_headline_trending_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_trending_headline',
            name='trending_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
