# Generated by Django 3.2.24 on 2024-12-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0011_rename_fname_comment_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='comm',
        ),
    ]
