# Generated by Django 3.2.24 on 2024-12-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0012_rename_comments_comment_comm'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_trending_col_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trending_photo', models.ImageField(upload_to='')),
                ('trending_type', models.CharField(choices=[('Food', 'Food'), ('Sport', 'Sport'), ('Design', 'Design'), ('Business', 'Business'), ('Tech', 'Tech'), ('Travel', 'Travel')], max_length=30)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=300)),
            ],
        ),
    ]
