# Generated by Django 3.2.24 on 2024-12-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0013_sub_trending_col_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_trending_col_1',
            name='trending_photo',
            field=models.ImageField(default='uploads/sub trending col 1/sub.jpg', upload_to='uploads/sub trending col 1'),
        ),
    ]
