# Generated by Django 3.2.24 on 2024-12-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0015_sub_trending_col_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_trending_col_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trending_title', models.CharField(max_length=300)),
                ('writter', models.ImageField(default='uploads/writters/writter.jpg', upload_to='uploads/writters')),
            ],
        ),
        migrations.AlterField(
            model_name='main_trending_headline',
            name='writter_photo',
            field=models.ImageField(default='uploads/writters/writter.jpg', upload_to='uploads/writters'),
        ),
    ]
