# Generated by Django 3.2.24 on 2024-12-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0016_auto_20241205_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_trending_col_3',
            name='writter',
            field=models.CharField(max_length=30),
        ),
    ]
