# Generated by Django 3.2.24 on 2024-12-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0018_auto_20241205_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_col1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('image', models.ImageField(default='uploads/comments/default.jpg', upload_to='uploads/comments')),
            ],
        ),
    ]
