# Generated by Django 3.2.24 on 2024-12-13 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0021_sub_trending_col_3_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_trending_col_3',
            name='trend_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
