# Generated by Django 3.2.24 on 2024-12-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0024_culture_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture_main',
            name='supporting_photo',
            field=models.ImageField(default='uploads/culture/culture.jpg', upload_to='uploads/culture'),
        ),
        migrations.AddField(
            model_name='culture_main',
            name='supporting_photo_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='culture_main',
            name='supporting_photo_title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
