# Generated by Django 3.2.24 on 2024-12-14 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0027_culture_col11'),
    ]

    operations = [
        migrations.CreateModel(
            name='culture_col12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='culture', max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=300)),
                ('brief_description', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('writer_name', models.CharField(max_length=30)),
            ],
        ),
    ]
