# Generated by Django 3.2.24 on 2024-12-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0028_culture_col12'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture_col12',
            name='brief_description',
        ),
    ]
