# Generated by Django 3.2.24 on 2024-12-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0030_comment_cul_col1'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_cul_col1',
            name='image',
            field=models.ImageField(default='uploads/comments/default.jpg', upload_to='uploads/comments'),
        ),
    ]
