# Generated by Django 3.2.24 on 2024-12-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0032_culture_col2'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture_col2',
            name='writer_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
