# Generated by Django 3.2.24 on 2024-12-17 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0033_culture_col2_writer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='culture_col3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='culture', max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=300)),
                ('writer_name', models.CharField(max_length=30)),
                ('photo', models.ImageField(default='uploads/culture/culture.jpg', upload_to='uploads/culture')),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
