# Generated by Django 3.2.24 on 2024-12-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0036_business_col1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_col1',
            name='type',
            field=models.CharField(default='Business', max_length=30),
        ),
    ]
