# Generated by Django 3.2.24 on 2024-12-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0043_comment_bus_col21'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField(default='')),
            ],
        ),
    ]
