# Generated by Django 3.2.24 on 2025-01-06 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0044_new_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='lifestyle_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='uploads/lifestyle/lifestyle.jpg', upload_to='uploads/lifestyle')),
                ('type', models.CharField(default='lifestyle', max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=300)),
                ('brief_description', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('writer_name', models.CharField(max_length=30)),
                ('writter_photo', models.ImageField(default='uploads/writters/writter.jpg', upload_to='uploads/writters')),
            ],
        ),
        migrations.CreateModel(
            name='lifestyle_main_support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supporting_photo', models.ImageField(default='uploads/lifestyle/lifestyle.jpg', upload_to='uploads/lifestyle')),
                ('supporting_photo_title', models.CharField(default='', max_length=300)),
                ('supporting_photo_description', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
