# Generated by Django 3.2.24 on 2025-01-06 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0045_lifestyle_main_lifestyle_main_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='lifestyle_col1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Lifestyle', max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=300)),
                ('writer_name', models.CharField(max_length=30)),
                ('photo', models.ImageField(default='uploads/lifestyle/lifestyle.jpg', upload_to='uploads/lifestyle')),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
