# Generated by Django 3.2.24 on 2025-01-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0047_comment_lifestyle_col1'),
    ]

    operations = [
        migrations.CreateModel(
            name='lifestyle_col_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trending_photo', models.ImageField(default='uploads/lifestyle_cole2/lifestyle.jpg', upload_to='uploads/lifestyle_col2')),
                ('trending_type', models.CharField(default='Lifestyle', max_length=30)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
