# Generated by Django 3.2.24 on 2025-01-08 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0051_comment_lifestyle_col3'),
    ]

    operations = [
        migrations.CreateModel(
            name='lifestyle_col_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Business', max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=300)),
                ('writer_name', models.CharField(max_length=30)),
                ('photo', models.ImageField(default='uploads/business/business.jpg', upload_to='uploads/business')),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
