# Generated by Django 3.2.24 on 2025-01-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0053_alter_lifestyle_col_4_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_lifestyle_col4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm', models.TextField()),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('image', models.ImageField(default='uploads/comments/default.jpg', upload_to='uploads/comments')),
            ],
        ),
    ]
