# Generated by Django 3.2.24 on 2025-01-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0054_comment_lifestyle_col4'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
            ],
        ),
    ]
